package emt.init;

import emt.gthandler.common.loader.EMT_GT_Loader;

public class Registry
{
  private static final EMT_GT_Loader gtloader = new EMT_GT_Loader();
  public static void registerPreInit() {
  }
  
  public static void registerInit()
  {
    EMTBlocks.registerBlocks();
	EMTItems.registerItems();
    EMTTiles.registerTileEntities();
    gtloader.run();
    EMTRecipes.registerEarlyRecipes();
  }
  
  public static void registerLate()
  {
    EMTBlocks.addAspects();
    gtloader.runlate();
    EMTRecipes.registerLateRecipes();
    EMTRecipes.registerUUMInfusionRecipes();
   // new EMTAutogeneratedGens().run();

  }
}
