package emt.init;

public class Registry
{
  public static void registerPreInit() {}
  
  public static void registerInit()
  {
    EMTBlocks.registerBlocks();
	EMTItems.registerItems();
    EMTTiles.registerTileEntities();
    EMTRecipes.registerEarlyRecipes();
  }
  
  public static void registerLate()
  {
    EMTBlocks.addAspects();
    EMTRecipes.registerLateRecipes();
    EMTRecipes.registerUUMInfusionRecipes();
   // new EMTAutogeneratedGens().run();
  }
}
