package emt.init;

import emt.gthandler.common.items.EMT_CasingBlock;
import emt.gthandler.common.loader.EMT_GT_Loader;

public class Registry
{
  public static void registerPreInit() {
  }
  
  public static void registerInit()
  {
    EMTBlocks.registerBlocks();
	EMTItems.registerItems();
    EMTTiles.registerTileEntities();
    new EMT_GT_Loader().run();
    EMTRecipes.registerEarlyRecipes();
  }
  
  public static void registerLate()
  {
    EMTBlocks.addAspects();
    EMTRecipes.registerLateRecipes();
    EMTRecipes.registerUUMInfusionRecipes();
   // new EMTAutogeneratedGens().run();
  }
}
